### ISSUE TITLE
a question about dimensional labels

### ISSUE THREAD

**Issue by harryxu-yscz** [aimerykong/Dimensional-Emotion-Analysis-of-Facial-Expression#1]
Thanks for sharing your work! 

Could you elaborate more on how are the dimensional labels for each image derived? The labels provided in your `imdb_DimEmotion.mat` seem to be normalized between 0 and 1 but from the equation in your paper it's not normalized.

**Comment by aimerykong** [comment]
Hi, Thanks for your interest.
I'm not exactly sure how the equation works as the labels were generated by my collaborator Dr. Feng Zhou. My initial guess is that, after obtaining all dimensional scores, we divided them by the maximum score so that all of them lie within [0, 1]. But please contact Dr. Feng Zhou for details.

**Comment by harryxu-yscz** [comment]
Thanks for the guidance! I emailed Dr. Feng Zhou about this.
Meanwhile, could you provide the normalized valence/arousal/dominance values for the fer+ labels?
The labels are: neutral, happiness, surprise, sadness, anger, disgust, fear, contempt

**Comment by aimerykong** [comment]
The labels used in our project can be found here 
https://drive.google.com/open?id=1s79cTqa9ftVfynUk0uZdQZUElozsaQ6l

The FER+ labels can be found here 
https://github.com/Microsoft/FERPlus

Hope this helps!

**Comment by harryxu-yscz** [comment]
Hi, the labels in the `imdb_DimEmotion.mat` are normalized dimensional scores for each image. I want to map the dimensional labels to the fer+ labels and calculate accuracy. What are the dimensional scores for the fer+ labels: neutral, happiness, surprise, sadness, anger, disgust, fear, contempt?

**Comment by aimerykong** [comment]
I see. It makes sense to reverse the dimensional score to the discrete labels to compare w.r.t accuracy. However, this is hard to do as the dimension scores are determined by all the labels in some way, and reversing it is an under-determined problem. I also thought about this way to compare with other classification-based methods, but it's non-trivial so that we couldn't do this.

**Comment by harryxu-yscz** [comment]
"Fine-Grained Facial Expression Analysis Us- ing Dimensional Emotion Model" provided a way to calculate accuracy in part V. I want to replicate that way for calculating accuracy. All I need are the valence/arousal/dominance mean values and standard deviation for the labels.

I tried to find these values from the ANEW and English Lemma paper. There are 2 problems I can't solve:
1. ANEW had labels for all, men, women categories and English Lemma had labels for Sum, Young, Old, Male, Female, High, Low categories. Which category did you use in your work?
2. What are the order of your label? i.e. are they arousal/valence/dominance, valence/arousal/dominance, etc. ?

Thus, I think it makes most sense for me to just ask for the scores for these labels

**Comment by aimerykong** [comment]
Hi, as I only have datasets with the two links, please contact Dr. Feng Zhou again for the data. He managed all the data, converted them, and sent me the final one used for training. Apologize for the inconvenience.

 arousal/valence/dominance is the correct order.

**Comment by harryxu-yscz** [comment]
I will ask Dr. Feng Zhou for these data then. Thanks!

**Comment by Doanhdz** [comment]
@harryxu-yscz  Sorry to bother you, can you show me how are the dimensional labels for each image derived?

**Comment by aimerykong** [comment]
Hi, Duy Anh,

Thanks for asking. Dr. Feng Zhou prepared the labeled data and he could
answer your question.

**Comment by Doanhdz** [comment]
Thanks for your reply, i will ask Dr. Feng Zhou.
